### ISSUE TITLE
bug: (Security Vulnerability) Unverified Score Submission

### ISSUE THREAD

**Issue by nicomenzi** [portdeveloper/slot-machine-monorepo#1]
### Is there an existing issue for this?

- [X] I have looked through the existing issues

### Current Behavior

The current implementation allows clients to send arbitrary scores to the backend without server-side verification. A malicious user can intercept the `setScore` request and modify it to submit any score they want, potentially manipulating the game's leaderboard or reward system.

### Expected Behavior

The server should verify the legitimacy of the submitted score based on the actual game play, preventing users from submitting arbitrary scores. For example the score gets "rendered" server side

### Steps To Reproduce

1. Play the slot machine game normally.
2. Use Postman Interceptor to intercept the /setScore request or reproduce the /setScore request in any desired tool
3. Modify the score value in the request body to any desired number.
4. Send the modified request.

**Comment by aurelien-cuvelier** [comment]
This can be fixed by hashing the payload with a secret that is commonly shared between the front and the back, the hash should be included in the request headers, and when the request is received by the backend, the payload should be hashed again including the secret, and compared to the hash in the headers.
If the hashes match the request is processed, if no then the data has been altered and the payload should be rejected.

A JWT implementation can also be done instead, but it seems to me to be a bit overkill in that case.

**Comment by portdeveloper** [comment]
fixed at #4
